name: Push to Dynamic Branches

on:
  push:
    branches:
      - '*' # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Target Branch
      if: github.ref != 'refs/heads/staging'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "kshitijdhama513.gmail.com"
        git checkout staging
        git commit -am "Automated commit from ${{ github.ref }} branch"
        git push origin ${{ github.ref }}
