name: Push to Dynamic Branches

permissions:
  contents: write

on:
  push:
    branches:
      - '*' # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Push to Target Branch
      if: github.ref != 'refs/heads/staging'
      run: |
        git config --global user.name 'kaydee0502'
        git config --global user.email 'kshitijdhama513@gmail.com'
        br=$(git rev-parse --abbrev-ref HEAD)
        git config user.name "GitHub Actions"
        git config user.email "kshitijdhama513.gmail.com"
        git fetch origin
        git checkout staging
        git pull origin $br --rebase -X theirs
        git pull origin staging --rebase -X ours
        git push origin staging
